<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dell-PC" name="different tetng feature test" tests="21" failures="2" timestamp="27 May 2020 05:21:11 GMT" time="41.406" errors="0">
  <testcase name="mailTextTest" time="0.176" classname="com.test.GoogleTest"/>
  <testcase name="GoogleLogoTest" time="0.091" classname="com.test.GoogleTest"/>
  <testcase name="GoogleTitleTest" time="0.01" classname="com.test.GoogleTest"/>
  <testcase name="GoogleTitleTest" time="0.001" classname="com.test.TestNgBasics"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.002" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="Invocationtest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="homepageSection1" time="0.001" classname="com.test.TestNgFeatures">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at com.test.TestNgFeatures.homepageSection1(TestNgFeatures.java:66)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- homepageSection1 -->
  <testcase name="invocationTimeOut" time="0.02" classname="com.test.TestNgFeatures">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.invocationTimeOut() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.invocationTimeOut() didn't finish within the time-out 2
	at com.test.TestNgFeatures.invocationTimeOut(TestNgFeatures.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- invocationTimeOut -->
  <testcase name="logintest" time="0.001" classname="com.test.TestNgFeatures"/>
  <testcase name="TryExpectedException" time="0.009" classname="com.test.TestNgFeatures"/>
  <testcase name="homepageSection2" time="0.0" classname="com.test.TestNgFeatures">
    <skipped/>
  </testcase> <!-- homepageSection2 -->
  <testcase name="homepageSection3" time="0.0" classname="com.test.TestNgFeatures">
    <skipped/>
  </testcase> <!-- homepageSection3 -->
  <testcase name="homepageTest" time="0.0" classname="com.test.TestNgFeatures"/>
</testsuite> <!-- different tetng feature test -->
